name: Respond to PR comments
on:
  issue_comment:
    # (ignore 'edited', 'deleted')
    types: [created]

jobs:
  pr_comment_hello:
    if: github.event.issue.pull_request && github.event.comment.body == '/hello'
    runs-on: ubuntu-latest
    steps:
      # (Don't need to check out repo)
      - name: Post ack comment
        # Docs: https://github.com/marketplace/actions/create-or-update-comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Comment received by workflow:
            ```
            ${{ toJSON(github.event.comment) }}
            ```

  pr_comment_trigger_secondary:
    name: "trigger secondary and post comment to PR"
    if: ${{ github.event.issue.pull_request && ['/run-online-tests', '/RUN-ONLINE-TESTS'].contains(github.event.comment.body) }}
    # Trigger the other workflow
    uses: ./.github/workflows/secondary.yaml
    with:
      pr_num: ${{ github.event.issue.number }}

  # pr_comment_trigger_secondary_no_pr:
  #   name: "trigger secondary without PR context"
  #   if: ${{ github.event.issue.pull_request && github.event.comment.body == '/run-online-tests-no-pr' }}
  #   uses: ./.github/workflows/secondary.yaml
