name: Respond to PR comments
on:
  issue_comment:
    # (ignore 'edited', 'deleted')
    types: [created]

jobs:
  pr_comment_trigger_secondary:
    name: "trigger secondary and post comment to PR"
    if: |
      github.event.issue.pull_request && (
        github.event.comment.body == 'RUN-ONLINE-TESTS' ||
        github.event.comment.body == 'run-online-tests' ||
        github.event.comment.body == 'RUN ONLINE TESTS' ||
        github.event.comment.body == 'run online tests' ||
      )
    # Trigger the other workflow
    # (which will also post comment(s) back to the calling PR)
    uses: ./.github/workflows/secondary.yaml
