name: Test secondary workflow

on:
  # Allow to be called by another workflow - specifically, by `pr-comments.yaml`.
  # In that case, `event` context (including branch/ref) is inherited from the calling PR.
  workflow_call:

  # Allow to be triggered manually
  workflow_dispatch:
    # no inputs / PR context here

jobs:
  fake_work:
    runs-on: ubuntu-latest
    steps:
      - name: Post job link to PR
        id: post_job_link
        if: github.event.issue && github.event.issue.number != null
        # Docs: https://github.com/marketplace/actions/create-or-update-comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Started secondary workflow.
            Inputs:
            ```
            ${{ toJSON(inputs) }}
            ```

            Github context:
            ```
            ${{ toJSON(github) }}
            ```

            Job context:
            ```
            ${{ toJSON(job) }}
            ```

            ${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}
            :hourglass_flowing_sand:

      - name: Pretend to do work
        shell: bash
        run: |
          echo "Hello world"
          if [[ "$(($RANDOM % 3))" == "0" ]]; then
            echo "Randomly failing"
            exit 1
          fi

      - name: Update PR comment on success
        if: |
          steps.post_job_link.outputs.comment-id != null &&
          steps.post_job_link.outcome == 'success'
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.post_job_link.outputs.comment-id }}
          edit-mode: append
          body: |
            ... Success! :white_check_mark: :peace_symbol:

      - name: Update PR comment on failure
        if: |
          steps.post_job_link.outputs.comment-id != null &&
          steps.post_job_link.outcome == 'failure'
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.post_job_link.outputs.comment-id }}
          edit-mode: append
          body: |
            ... Failed! :exclamation: :warning:
