name: Test secondary workflow

on:
  # Allow to be called by another workflow - specifically, by `pr-comments.yaml`.
  # In that case, the branch/ref is inherited from the calling PR.
  workflow_call:
    inputs:
      pr_num:
        description: "PR number in which to post a comment with link to test run"
        # default: null
        required: false
        type: number

  # Allow to be triggered manually
  workflow_dispatch:
    # no inputs / PR context here

jobs:
  "secondary":
    runs-on: ubuntu-latest
    steps:
      - name: ack
        run: |
          echo "Ack"

      - name: Post comment
        if: ${{ inputs.pr_num != null }}
        # Docs: https://github.com/marketplace/actions/create-or-update-comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ inputs.pr_num }}
          body: |
            Started secondary workflow.
            Inputs:
            ```
            ${{ toJSON(inputs) }}
            ```

            Github context:
            ```
            ${{ toJSON(github) }}
            ```

            Job context:
            ```
            ${{ toJSON(job) }}
            ```

            ${{ github.event.repository.html_url }}/actions/runs/{{ github.event.run_id }}
